### ISSUE TITLE
Critical: Paho 1.0.10/1.0.11 stop reading after some messages

### ISSUE THREAD

**Issue by rgaufman** [RubyDevInc/paho.mqtt.ruby#38]
Hi there,

I had to revert to 1.0.9 because on 1.0.10 and 10.0.11 the subscriber receives a handful of messages and then stops completely :( 

Any ideas what could be causing it?

**Comment by p-goudet** [comment]
@rgaufman  Thank you again for your following.
Is this issue occurs every times? I found some strange things when qos=2 that I do not see with qos = 1. I am still investigating on what happened.

Do you have more details/logs related with this bug?

**Comment by rgaufman** [comment]
Yes, qos=2 and happens every single time. To reproduce:

1. Write a few thousand messages to Mosquitto
2. Subscribe in ruby paho with a client_id that has clean_session: false and qos: 2

It reads a few messages and freezes. No errors, nothing in the log :(

**Comment by p-goudet** [comment]
Well I think I found what was wrong. When qos=2, acknowledge message where not handle properly.
My apologies for this mistake, I am currently fixing it, I would give you news soon.

**Comment by rgaufman** [comment]
Thank you for the update :) - will test the new version as soon as it is ready.

**Comment by p-goudet** [comment]
I publish a new version 1.0.11 which I hope should fix this issues and the previous one :).

**Comment by rgaufman** [comment]
I checked 1.0.11 and it's the same situation :( - it reads a few messages and then stops. Reverted back to 1.0.9 which works correctly.

**Comment by p-goudet** [comment]
My apologies, I will keep checking what is wrong so. :,(

**Comment by rgaufman** [comment]
Thank you for looking into this, I'm just trying to write some code to help reproduce this, will follow up shortly :)

**Comment by p-goudet** [comment]
Thank you very much. 
Could you tell me more about the environment when the issue occurs? (qos, persistence, only sending, sending and receiving, etc...)
I would try to reproduce it as well.

**Comment by rgaufman** [comment]
It's strange, I've been trying to reproduce the issue on my local machine but not able to, but for some reason it happens on the production server, hmm. This is my code:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'paho-mqtt', '= 1.0.11'
end

publish_to = '/test_session'
topics = [["#{publish_to}/#", 2]]
Messages = Queue.new

def new_client(clean_session: false, client_id: 'test_consumer')
  puts "Starting client with clean_session: #{clean_session} and " \
       "client_id: #{client_id}"
  client = PahoMqtt::Client.new(
    clean_session: clean_session, client_id: client_id,
    persistent: true, reconnect_limit: 1000, reconnect_delay: 1,
    keep_alive: 29, ack_timeout: 10,
  )
  client.connect('127.0.0.1', '1884')
  client
end

def sub(client, topics)
  client.on_suback do
    puts "Successfully Subscribed"
  end

  client.on_message do |msg|
    yield [msg.topic, msg.payload]
  end

  client.subscribe(topics)
end

def worker(queue)
  loop do
    topic, payload = queue.pop
    puts "#{topic} :: #{payload}"
  end
end
Thread.new { worker(Messages) }

# 1) Remove any previous persistent session (starting clean)
client = new_client(clean_session: true)
sleep 1
client.disconnect

# 2) Create a persistent session
client = new_client
client.subscribe(topics)
sleep 1
client.disconnect

# 3) We have a disconnected session now, lets write messages from a temp client
client = new_client(clean_session: true, client_id: nil)
(1..10_000).each do |i|
  client.publish(publish_to, "The big brown fox jumped over the lazy dog, The big brown fox jumped over the lazy dog, The big brown fox jumped over the lazy dog, The big brown fox jumped over the lazy dog The big brown fox jumped over the lazy dog #{i}", false, 2)
  # sleep 0.0001
end
sleep 5 # Give some time for the messages to publish
client.disconnect

# 4) We should now be able to subscribe and get all the messages at once
client2 = new_client
sub(client2, topics) do |msg|
  Messages << msg
end

loop { sleep 60 }
```

**Comment by p-goudet** [comment]
Thank you very much for this samples. I tried this on my environment, with a simple mosquitto message broker. Here is what happened: 
All four step are execute:
the first step connect and disconnect, the 
100 message are displayed and then the programs just sleep while the client 'test_consumer' is still connected.

**Comment by rgaufman** [comment]
I just tried again in production this time with PahoMqtt.logger = 'log/paho.log'

My code is similar to the above and it works with 'paho-mqtt', '= 1.0.9' but with 1.0.11 I see this: ﻿https://www.dropbox.com/s/6qukxdpwtpq146b/paho.log?dl=0

It's strange that I can't reproduce this on my local machine.

Any ideas?

**Comment by rgaufman** [comment]
I also ran a few different times, making tweaks to my code and then I saw a bunch of these:
```
E, [2018-05-26T14:28:48.927139 #12586] ERROR -- : Writing queue is full, slowing down
```

However, in the source code, it doesn't appear to rescue/retry from this? - or am I missing something?

```ruby
    def prepare_sending(queue, mutex, max_packet, packet)
      if queue.length < max_packet
        mutex.synchronize do
          queue.push(packet)
        end
      else
        PahoMqtt.logger.error('Writing queue is full, slowing down') if PahoMqtt.logger?
        raise FullWritingException
      end
end
```

**Comment by p-goudet** [comment]
@rgaufman Thank for your effort.

I would try to answer to the different points, please tell me if you think something is unclear or wrong.

1) Why pubrec queue could be full even with a client that only subscribe?
- The client that subscribe to a topics need to acknowledge incoming message with qos=1 (PUBACK) and with qos=2 (PUBREC then PUBCOMP). In this case you are using  qos=2, when a publish packet is read, the handler would create a PUBREC packet, store it in a queue, waiting to be sent. I could not reproduce the issue yet, as it occurs on your production server. It might occurs because of a difference between the reading queue capacity and the handling queues capacities. I can not confirm this and I am still working it.

2) Is `FullWritingException` exception handled?
- Yes, it is... but no inside the `prepare_sending` method : 
```ruby
   def append_to_writing(packet)
      begin
        if packet.is_a?(PahoMqtt::Packet::Publish)
          prepare_sending(@publish_queue, @publish_mutex, MAX_PUBLISH, packet)
        else
          prepare_sending(@writing_queue, @writing_mutex, MAX_QUEUE, packet)
        end
      rescue FullWritingException
        sleep SELECT_TIMEOUT
        retry
      end
      MQTT_ERR_SUCCESS
    end
```
Maybe the exception handling should be moved to the  `prepare_sending` method, but I do not think this is the cause of this issue. If you are seeing a bunch of errors in a short time, I think it means that the `retry` instructions has been executed.

**Comment by p-goudet** [comment]
I could reproduce similar error. I think that it is due to a deadlock issue, due to two thing:
- The capacity of handling queue was shorter than the reading capacity. A `FullQueueException` would be raised as the handling queue get full before the reading process finish
- The exception handler is retrying inside the reading process, and it does not enable the writing to be executed.

 Basically it will try to store new pubrec packet in queue which is already full. Pubrec packet can not be send because of the `FullQueueException` handler that would retry forever in the reading process.

I am keeping working it. I hope it would be solved soon now I could find what happened.

**Comment by rgaufman** [comment]
Thank you very much for looking at this :)

**Comment by p-goudet** [comment]
@rgaufman Thank you for your contribution. The version 1.0.12 is released, could you tell me if you find any remaining issues?

**Comment by rgaufman** [comment]
All working beautifully on 1.0.12, thank you!!

**Comment by jurek7** [comment]
@p-goudet I reproduced this issue in my logstash-mqtt-plugin
https://github.com/jurek7/logstash-input-mqtt/issues/5

Could you please take a look on that ?

**Comment by p-goudet** [comment]
@jurek7 
Thank you.
I will try to find out what happen.
